<?php
// $Id$

/**
 * @file
 * Views extensions for argument defaults for the current node's terms
 */

/**
 * Implementation of hook_views_api().
 */
function views_term_argument_default_views_api() {
  return array(
    'api'  => 2.0,
    'path' => drupal_get_path('module', 'views_term_argument_default') . '/includes',
  );
}

function views_term_argument_default_node_get_terms($nid) {
  static $terms;

  if (!isset($terms[$nid])) {
    $result = db_query(db_rewrite_sql('SELECT t.tid, t.vid FROM {term_node} r INNER JOIN {term_data} t ON r.tid = t.tid INNER JOIN {node} n ON r.vid = n.vid WHERE n.nid = %d', 't', 'tid'), $nid);
    $terms[$nid] = array();
    while ($term = db_fetch_object($result)) {
      $terms[$nid][$term->tid] = $term;
    }
  }
  return $terms[$nid];
}
